// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrhmjglhjfbcovvgctuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyaG1qZ2xoamZiY292dmdjdHVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MDkwMTIsImV4cCI6MjA3MzA4NTAxMn0.rtI3kHFVsgMJTUGaXq6j9_IE_ggX6x9UqGm37iikSHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});